import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import TRPCReactProvider from '@/trpc/client';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Meet.AI',
  description: 'Generated by Meet.AI',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
